// <auto-generated />
namespace MVCApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201911121221590_UpdataAfterDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201911121221590_UpdataAfterDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201911121225198_201911121221590_UpdataAfterDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
